### ISSUE TITLE
US011 Obtener la cantidad de productos en promoción de un determinado vendedor

### ISSUE THREAD

**Issue by InakiEtc** [InakiEtc/be_java_hisp_w28_g03#12]

**Comment by vilo0812** [comment]
Obtener la cantidad de productos en promoción de un determinado vendedor

**Comment by vilo0812** [comment]
<tbody><tr class="c8"><td class="c35" colspan="1" rowspan="1"><p class="c0"><span class="c11">Method</span></p></td><td class="c61 c60" colspan="1" rowspan="1"><p class="c0"><span class="c11">SIGN</span></p></td></tr><tr class="c8"><td class="c105" colspan="1" rowspan="1"><p class="c3"><span class="c7">GET</span></p></td><td class="c61" colspan="1" rowspan="1"><p class="c0 c5"><span class="c6">/products/promo-post/count?user_id={userId}</span></p></td></tr><tr class="c8"><td class="c35" colspan="1" rowspan="1"><p class="c0"><span class="c4 c16 c26">Response</span></p></td><td class="c27" colspan="1" rowspan="1"><p class="c0 c5"><span class="c2">{ &nbsp;</span></p><p class="c0 c5"><span class="c2">&nbsp; &nbsp;"user_id" : 234,</span></p><p class="c0 c5"><span class="c2">&nbsp; &nbsp;"user_name": "vendedor1",</span></p><p class="c0 c5"><span class="c2">&nbsp; &nbsp;"promo_products_count": 23</span></p><p class="c0 c5"><span class="c2">}</span></p></td></tr></tbody>
