### ISSUE TITLE
US005 - Dar de alta una nueva publicacion

### ISSUE THREAD

**Issue by InakiEtc** [InakiEtc/be_java_hisp_w28_g03#6]

**Comment by Juan-Bianchi** [comment]
Agrego Requerimientos del enpoint

<p class="c85 c10" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Arial; padding-top: 16pt; padding-bottom: 10pt; line-height: 1.15; text-align: justify; orphans: 2; widows: 2; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="c18 c23" style="font-size: 12pt; font-family: &quot;Proxima Nova&quot;; color: rgb(67, 67, 67); font-weight: 700; text-decoration: underline; text-decoration-skip-ink: none;">US 0005:</span><span class="c18" style="font-size: 12pt; font-family: &quot;Proxima Nova&quot;; color: rgb(67, 67, 67); font-weight: 700;"> </span><span class="c22" style="color: rgb(67, 67, 67); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 12pt; font-family: &quot;Proxima Nova&quot;; font-style: normal;">Dar de alta una nueva publicación</span></p><p class="c10 c96" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Arial; padding-top: 10pt; padding-bottom: 0pt; line-height: 1.15; text-align: justify; orphans: 2; widows: 2; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="c18 c23" style="font-size: 12pt; font-family: &quot;Proxima Nova&quot;; color: rgb(67, 67, 67); font-weight: 700; text-decoration: underline; text-decoration-skip-ink: none;">Sign</span><span class="c6" style="color: rgb(67, 67, 67); font-weight: 700; text-decoration: none; vertical-align: baseline; font-size: 12pt; font-family: &quot;Proxima Nova&quot;; font-style: normal;">:</span></p>


Method | SIGN
-- | --
POST | /products/post


PAYLOAD: {   
     "user_id": 123,    
     "date": "29-04-2021",    
     "product": {        
                "product_id": 1,        
                "product_name": "Silla Gamer",        
                 "type": "Gamer",       
                 "brand": "Racer",        
                 "color": "Red & Black",        
                 "notes": "Special Edition"    
     },    
     "category": 100,   
     "price": 1500.50
}


RESPONSE 
Status Code 200 (todo OK)
Status Code 400 (Bad Request)

**Comment by Juan-Bianchi** [comment]
US 0007:  “Unfollow” (dejar de seguir) a un determinado
vendedor.
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		
			
Method | SIGN
-- | --
POST | /users/{userId}/unfollow/{userIdToUnfollow}
Ejemplo: /users/234/unfollow/123


				
Parámetros | Tipo | Descripción/Ejemplo
-- | -- | --
userId | int | Número que identifica a cada usuario
