### ISSUE TITLE
US007 - Dejar de seguir a un usuario

### ISSUE THREAD

**Issue by InakiEtc** [InakiEtc/be_java_hisp_w28_g03#8]

**Comment by Juan-Bianchi** [comment]
US 0007:  “Unfollow” (dejar de seguir) a un determinado
vendedor.
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		
			
Method | SIGN
-- | --
POST | /users/{userId}/unfollow/{userIdToUnfollow}
Ejemplo: /users/234/unfollow/123


				
Parámetros | Tipo | Descripción/Ejemplo
-- | -- | --
userId | int | Número que identifica a cada usuario
